### PR TITLE
Fix memleak on non-icon drag in drag_routines.c with custom dragging …

### PR DESCRIPTION
**Pull request by Hagbard-Celin**
…enabled

I just mirrored part of what was done in commit b0799cd. This seems to work after a quick test.

### CODE REVIEW

**Comment by mheyer32** [comment]
Should there be symmetrical call to RemVSprite?

**Comment by Hagbard-Celin** [comment]
If I understand the code correctly it is already there in L_RemoveDragImage() only it is done manually and not using RemVSprite() (Unless RemVSprite() does something more that is needed). Gets called from L_RemDragImage(). It seems to work like this in my build.

Edited because my recollection mixed up RemBob and RemVSprite as to which one was a macro.
Edit 2: Not quite awake here: It is not end of, but whole L_RemoveDragImage(), also line-numbers where wrong so removed them.

**Comment by mheyer32** [comment]
I see that L_RemoveDragImage indeed does remove the image from the sprites list. Would it make sense to use RmVSprite() there?

**Comment by Hagbard-Celin** [comment]
I'm not sure, it will probably work, but as I understand it one of the main ideas behind custom-dragging is replacing system-library-calls with custom inline code.
I went by the rule: do the minimum amount of change required to fix the problem. 

It is easily testable by opening a function editor, start dragging a command, and just release it over a empty spot on the desktop.
Before it would loose about as much ram as the icon dragging before your fix. Now it will lose nothing.
To really prove that it looses noting one can do the following:
1. Open "Lister->Edit Lister Toolbar..." from menu.
2. With only "toolbar" and "Button Bank Editor" windows open, make a note of available/used memory (or use a tool like MemLeakZ).
3. double click a button to edit it.
4. Select "Edit Function..." in "Button editor".
5. Grab a command from the list in "Function Editor", drag it to an empty spot on desktop an release.
6. Close "Function Editor" and  "Button Editor" by close gadget or "Cancel" button.
7. Compare available/used memory to step 2.

**Comment by mheyer32** [comment]
At least we left some discussion trail here for future reference :-)

**Pull request merged**
