### PR TITLE
Fixed memory leak when using custom drag routines

### PR DESCRIPTION
**Pull request by midwan**

### CODE REVIEW

**Comment by mheyer32** [comment]
Thanks for this MR. Could you please extend the commit message to
a) what the problem was
b) how this patch fixes it

One thing I don't understand is why we're using vsprites. Dragged Icons can be of any size, so clearly they should be Bobs, no?

**Comment by mheyer32** [comment]
In fact, I can't observe a memory leak with Top-of-tree DOpus. I am highly doubtful that the proposed patch is correct.
Can you confirm that you observe memory leaks without your patch?

**Comment by midwan** [comment]
@mheyer32 
I can recreate the memory leak with the binaries of 5.91 (when using a P96 screen, just dragging an icon will eat up RAM that is not freed afterwards. Drag another icon, more RAM goes away, etc).

I noticed that the sources are building v5.92 of course, but I didn't test with an unmodified binary of that to see if that behaves differently regarding this issue, than v5.91. But I can test that also later today and see.

As for the reasoning behind this, I can only offer what explanation PeterK did - this was just a quick way to get the same "fix" in the latest sources. :)

**Comment by midwan** [comment]
Confirmed: I can recreate the memory leak problem even with the unmodified sources of 5.92.
And at the same time, the leak seems to be fixed after applying the fixes in this PR, and following the same steps to recreate.

Keep in mind you'll only see the leak if you're using the custom drag routines, and a P96 screen.

**Comment by mheyer32** [comment]
I debugged this issue and now understand the VSprite business. The DOpus  drag'n'drop stuff is messy :-) 
I found an adequate fix: b0799cd99cc1ba5531f390dcde3cf2a923d04f72  and submitted it.

**Comment by midwan** [comment]
Good job!

**Comment by mheyer32** [comment]
Unfortunately, the 'fix' broke double-clicking on icons **facepalm**

**Pull request closed without merging**
