### PR TITLE
Added automated builds for os3

### PR DESCRIPTION
**Pull request by midwan**
This adds automated builds for AmigaOS3 (feel free to add other targets if you want or let me know if you need help with that). It uses docker and GCC to generate the builds and uploads the resulting artifact in the pipeline.
It can be easily extended to generate full releases as well, if that is required.

### CODE REVIEW

**Comment by midwan** [comment]
@mheyer32 
Did you get a chance to look at this yet? :)

**Comment by mheyer32** [comment]
Oh man, I totally overlooked your MR. Better make some more noise next time :-)
I'll merge now. Thank you for sharing your improvements!
This is a great addition!

**Comment by midwan** [comment]
@mheyer32 
I just noticed that with the recent update to use the NDK 3.2, the build fails using the docker container (which includes NDK 3.9). Reverting that commit allows it to build again.

I'm still not sure why it fails, but worth keeping in mind for now!

**Comment by mheyer32** [comment]
Well yeah, it now fails for me locally :-(
I think the docker may be out of date!

**Comment by midwan** [comment]
@mheyer32 The docker container comes from here: https://github.com/AmigaPorts/docker-amiga-gcc
It's usually updated quite often, last commit was 2 weeks ago.

**Comment by mheyer32** [comment]
Maybe the docker image needs to switch to the "amiga6" branch via
`make branch amiga6`
AFAIR, that caused my local install to switch NDK to 3.2

**Comment by midwan** [comment]
@mheyer32 
AFAIK, the docker image does not contain the NDK3.2 - I asked Marlon about it, and he said that it caused problems with a lot of projects. You can of course include anything extra by adding those in the parameters, but the included NDK is still 3.9 and I'm not sure if it will work properly this way. Perhaps the best way would be to have a separate image, or not include any NDK at all.

The default branch is already GCC 6, there is an experimental GCC 10 option as well for the newer compiler.

**Pull request merged**
